load("//mediapipe/java/com/google/mediapipe:mediapipe_aar.bzl", "mediapipe_aar")
mediapipe_aar(
	name = "mp_iris_tracking",
	calculators = ["//mediapipe/graphs/iris_tracking:iris_tracking_gpu_deps"],
)
